[project]
name = "voice-project"
version = "0.2.0"
requires-python = ">=3.10,<3.13"
dependencies = [
    "torch>=2.2.0",
    "faster-whisper>=1.1.0",
    "nemo-toolkit[asr]>=2.0.0",
    "librosa>=0.11.0",
    "soundfile>=0.13.1",
    "omegaconf>=2.3.0",
    "pyqt6>=6.4.0",
    "datasets>=3.0.0",
    "torchcodec>=0.13.0",
    "yt-dlp>=2024.0.0",
    "kaggle>=1.7.4.5",
    "matplotlib>=3.10.9",
    "scipy>=1.15.3",
    "python-docx>=1.2.0",
    "python-levenshtein>=0.27.3",
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
